# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0002_mascota_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Aseo', 'Aseo'), ('Medico', 'Medico'), ('Alimento', 'Alimento')], max_length=10)),
                ('actividad', models.CharField(max_length=150)),
                ('hora', models.TimeField()),
                ('lunes', models.NullBooleanField()),
                ('martes', models.NullBooleanField()),
                ('miercoles', models.NullBooleanField()),
                ('jueves', models.NullBooleanField()),
                ('viernes', models.NullBooleanField()),
                ('sabado', models.NullBooleanField()),
                ('domingo', models.NullBooleanField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('completado', models.BooleanField(default=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota')),
            ],
        ),
    ]
