# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio',
            name='categoria',
            field=models.CharField(choices=[('Aseo', 'Aseo'), ('Medico', 'Medico'), ('Alimento', 'Alimento'), ('Otro', 'Otro')], max_length=10),
        ),
    ]
