# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorio', '0004_recordatorio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recordatorio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
