# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorio', '0005_auto_20171130_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
