# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorio', '0006_auto_20171201_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificadorRecordatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(default=1)),
                ('recordatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordatorio.Recordatorio')),
            ],
        ),
    ]
