# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorio', '0007_identificadorrecordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio',
            name='hora',
            field=models.TimeField(default='08:00'),
        ),
    ]
