# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioMapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('latitud', models.FloatField(max_length=30)),
                ('longitud', models.FloatField(max_length=30)),
                ('telefono', models.BigIntegerField()),
                ('horario', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo_sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_sitio.TipoSitio')),
            ],
        ),
    ]
