# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_mapa', '0002_sitiomapa_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitiomapa',
            name='descripcion',
        ),
    ]
