# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0008_mascota_esterilizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaMascotaGenero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota')),
            ],
        ),
    ]
