# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 17:14
from __future__ import unicode_literals

import apps.historial_medicamento.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0008_mascota_esterilizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10)),
                ('medicamento', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to=apps.historial_medicamento.models.upload_location)),
                ('dosis', models.CharField(max_length=15)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota')),
            ],
        ),
    ]
