# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medicamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
