# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 15:52
from __future__ import unicode_literals

import apps.historial_medicamento.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20171116_1931'),
        ('medicamento', '0001_initial'),
        ('historial_medicamento', '0002_historialmedico_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to=apps.historial_medicamento.models.upload_location)),
                ('dosis', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=100)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamento.Medicamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='historialmedico',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='historialmedico',
            name='medicamento',
        ),
        migrations.DeleteModel(
            name='HistorialMedico',
        ),
    ]
