# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medicamento', '0003_auto_20171127_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedicamento',
            name='dosis',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='historialmedicamento',
            name='observacion',
            field=models.CharField(max_length=200),
        ),
    ]
