# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medicamento', '0004_auto_20171127_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedicamento',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialmedicamento',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota'),
        ),
    ]
