# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medicamento', '0005_auto_20171128_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedicamento',
            name='observacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
