# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliado',
            name='sitio',
            field=models.URLField(blank=True, default=''),
        ),
    ]
