# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliado', '0002_aliado_sitio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliado',
            name='sitio',
            field=models.URLField(),
        ),
    ]
