# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 04:20
from __future__ import unicode_literals

import apps.mascota_premium.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0006_auto_20171116_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaPremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microchip', models.TextField(max_length=15)),
                ('codigoqr', models.ImageField(upload_to=apps.mascota_premium.models.upload_location)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota')),
            ],
        ),
    ]
