# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 16:59
from __future__ import unicode_literals

import apps.mascota_premium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota_premium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotapremium',
            name='codigoqr',
            field=models.ImageField(blank=True, upload_to=apps.mascota_premium.models.upload_location),
        ),
    ]
