# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota_premium', '0003_auto_20171212_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotapremium',
            name='microchip',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
