# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:50
from __future__ import unicode_literals

import apps.mascota_calle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaCalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to=apps.mascota_calle.models.upload_location)),
                ('latitud', models.FloatField(max_length=40)),
                ('longitud', models.FloatField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
            ],
        ),
    ]
