# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota_calle', '0002_mascotacalle_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotacalle',
            name='observacion',
            field=models.CharField(max_length=100),
        ),
    ]
