# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_vacuna', '0002_historialvacuna_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialvacuna',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=20),
        ),
    ]
