# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_vacuna', '0004_auto_20171114_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialvacuna',
            name='observacion',
            field=models.CharField(max_length=200),
        ),
    ]
