# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historial_vacuna', '0005_auto_20171127_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialvacuna',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota'),
        ),
    ]
