# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_vacuna', '0006_auto_20171127_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialvacuna',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
