# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna', '0001_initial'),
        ('historial_vacuna', '0007_auto_20171127_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialvacuna',
            name='vacuna',
        ),
        migrations.AddField(
            model_name='historialvacuna',
            name='vacuna',
            field=models.ManyToManyField(to='vacuna.Vacuna'),
        ),
    ]
