# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20171215_1540'),
        ('historial_vacuna', '0008_auto_20171218_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialvacuna',
            name='vacuna_usuario',
            field=models.ManyToManyField(to='usuario.VacunaUsuario'),
        ),
    ]
