# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_vacuna', '0010_remove_historialvacuna_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialvacuna',
            name='vacuna_usuario',
            field=models.ManyToManyField(blank=True, null=True, to='usuario.VacunaUsuario'),
        ),
    ]
