# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_vacuna', '0012_auto_20171219_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialvacuna',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='vacuna.Vacuna'),
        ),
        migrations.AlterField(
            model_name='historialvacuna',
            name='vacuna_usuario',
            field=models.ManyToManyField(blank=True, to='usuario.VacunaUsuario'),
        ),
    ]
