# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaPerdida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('latitud', models.FloatField(max_length=40)),
                ('longitud', models.FloatField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('celular', models.BigIntegerField()),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota')),
            ],
        ),
    ]
