# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 23:35
from __future__ import unicode_literals

import apps.mascota_perdida.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota_perdida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotaperdida',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='mascotaperdida',
            name='longitud',
        ),
        migrations.AddField(
            model_name='mascotaperdida',
            name='volante',
            field=models.ImageField(blank=True, null=True, upload_to=apps.mascota_perdida.models.upload_location),
        ),
    ]
