# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota_perdida', '0002_auto_20171214_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotaperdida',
            name='mascota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mascota_perdida', to='mascota.Mascota'),
        ),
    ]
