# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_mascota', '0001_initial'),
        ('mascota', '0002_mascota_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='raza',
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo_mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipo_mascota.TipoMascota'),
            preserve_default=False,
        ),
    ]
