# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raza', '0001_initial'),
        ('mascota', '0003_auto_20171115_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='tipo_mascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='raza.Raza'),
            preserve_default=False,
        ),
    ]
