# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20171116_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='dia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='mes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
