# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20171116_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.FloatField(),
        ),
    ]
