# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20171116_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='aseguradora',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mascota',
            name='numero_contacto',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='mascota',
            name='numero_poliza',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
