# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_auto_20171201_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(default=False),
        ),
    ]
