# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 22:30
from __future__ import unicode_literals

import apps.tipo_sitio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('marcador', models.ImageField(upload_to=apps.tipo_sitio.models.upload_location)),
            ],
        ),
    ]
