# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raza',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
