# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 04:20
from __future__ import unicode_literals

import apps.media_mascota.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0006_auto_20171116_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=apps.media_mascota.models.upload_location)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='mascota.Mascota')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
