# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFacebook', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('verificado', models.BooleanField(default=True)),
                ('telefono', models.BigIntegerField(blank=True, default=0)),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
