# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20171114_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('puede_agregar_premium', 'Puede agregar a premium'),)},
        ),
        migrations.AddField(
            model_name='usuario',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
