# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idFacebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
