# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0001_initial'),
        ('usuario', '0005_auto_20171208_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacunaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ciudad.Ciudad'),
        ),
        migrations.AddField(
            model_name='vacunausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
