# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20171215_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunausuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
