# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20171219_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunausuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
