# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20171219_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunausuario',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='vacunausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
