# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0012_auto_20171219_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
