# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_usuario_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_token',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
