# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_auto_20171221_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='verificado',
        ),
    ]
